- name: variables from files
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: print variables data
    ansible.builtin.debug:
      msg: "hi I am learning {{COURSE}},and the trainer is {{TRAINER}},and duration is: {{DURATION}}"