- name: conditions to check the given number
  hosts: local
  vars_prompt:
  - name: my_number
    prompt: please enter the number
    private: false
  tasks:
  - name: print this if given number less than 10
    ansible.builtin.debug:
      msg: "given number {{my_number}} is less than 10 "
    when: my_number | int < 10

  - name: print this if given number grater than 10
    ansible.builtin.debug:
      msg: "given number {{my_number}} is grater than 10 "
    when: my_number | int >= 10