- name: install nginx
  hosts: web
  become: yes
  tasks:
  - name: print the stats
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"
  
  - name: install if redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"
      msg:  "redHat installed"

     
  - name: install if Debian
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"
      msg:  "redHat installed"





